exports.ErrorCode = {
  ADMIN_EMAIL_IS_EXIST: 'Email admin is alreay exists',
  PARTNER_EMAIL_IS_EXIST: 'Email partner is alreay exists',
  EMPLOYEE_EMAIL_IS_EXIST: 'Email employee is alreay exists',
  EMAIL_NOT_REGISTERED: 'Email is not registered',
  PASSWORD_NOT_MATCH: 'Password is not match',
  ROLE_NOT_FOUND: 'Role is not found',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  INTERNAL_SERVER_ERROR: 'Internal server error',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  EXPIRED_REFRESH_TOKEN: 'Expired refresh token',
  COMPANIES_NOT_FOUND: 'List companies not found',
  EMPLOYEES_NOT_FOUND: 'List employees not found',
  PROMOTIONS_NOT_FOUND: 'List promotions not found',
  EMPLOYEE_INFO_NOT_FOUND: 'Employee info not found',
  PARTNER_INFO_NOT_FOUND: 'Partner info not found',
  NOT_AUTHORIZED: 'Not authorized',
  FORBIDDEN: 'You are not allowed to access this resource',
  PARAMS_NOT_FOUND: 'Paramas not found',
};
